"""
Domain Ports (Interfaces)

Following skill2026.md Rule 2 - Interface-First Development.
Ports are defined in the domain layer, implementations are in infrastructure.
"""

from typing import Protocol, Any
from collections.abc import AsyncIterator

from ..entities import NeuralSignal, CognitiveState, Device, User, Session
from ..value_objects import ClassificationResult, DeviceCommand, DeviceStatus


class SignalRepositoryPort(Protocol):
    async def save(self, signal: NeuralSignal) -> None: ...
    async def get_by_id(self, signal_id: str) -> NeuralSignal | None: ...
    async def get_by_session(self, session_id: str) -> list[NeuralSignal]: ...
    async def delete(self, signal_id: str) -> None: ...


class CognitiveClassifierPort(Protocol):
    async def classify(self, signal: NeuralSignal) -> ClassificationResult: ...
    async def train(
        self, user_id: str, signals: list[NeuralSignal], labels: list[str]
    ) -> None: ...


class DeviceControllerPort(Protocol):
    async def connect(self, device_id: str) -> bool: ...
    async def disconnect(self, device_id: str) -> bool: ...
    async def send_command(self, device: Device, command: DeviceCommand) -> bool: ...
    async def get_status(self, device_id: str) -> DeviceStatus: ...


class UserRepositoryPort(Protocol):
    async def save(self, user: User) -> None: ...
    async def get_by_id(self, user_id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def delete(self, user_id: str) -> None: ...


class SessionRepositoryPort(Protocol):
    async def save(self, session: Session) -> None: ...
    async def get_by_id(self, session_id: str) -> Session | None: ...
    async def get_by_user(self, user_id: str) -> list[Session]: ...
    async def get_active_session(self, user_id: str) -> Session | None: ...


class EventBusPort(Protocol):
    async def publish(self, events: list[Any]) -> None: ...
    async def subscribe(self, event_type: type, handler: Any) -> None: ...


class SignalAcquisitionPort(Protocol):
    async def start_acquisition(
        self, session_id: str, channels: list[str]
    ) -> AsyncIterator[NeuralSignal]: ...
    async def stop_acquisition(self) -> None: ...
