"""
Domain Ports (Interfaces)

Following skill2026.md Rule 2 - Interface-First Development.
Ports are defined in the domain layer, implementations are in infrastructure.
"""

from typing import Protocol, Any
from collections.abc import AsyncIterator


class ToolRegistryPort(Protocol):
    async def register(self, manifest: Any) -> None: ...
    async def get(self, tool_name: str) -> Any | None: ...
    async def list_all(self) -> list[Any]: ...
    async def validate_signature(self, manifest: Any) -> bool: ...


class ExecutionPort(Protocol):
    async def create_session(self, agent_id: str, created_by: str) -> Any: ...
    async def get_session(self, session_id: str) -> Any | None: ...
    async def validate_token(self, token: str) -> bool: ...
    async def execute_tool(
        self, session: Any, tool_name: str, parameters: dict
    ) -> Any: ...


class CorrectionStorePort(Protocol):
    async def save_correction(self, correction: Any) -> None: ...
    async def get_correction(self, correction_id: str) -> Any | None: ...
    async def find_patterns(self, intent_vector: tuple[float, ...]) -> list[Any]: ...
    async def update_pattern(self, pattern: Any) -> None: ...


class PolicyEnginePort(Protocol):
    async def evaluate(self, policy: Any, context: dict) -> bool: ...
    async def add_policy(self, policy: Any) -> None: ...
    async def remove_policy(self, policy_id: str) -> None: ...
    async def list_policies(self) -> list[Any]: ...


class AuditLogPort(Protocol):
    async def write(self, event: Any) -> None: ...
    async def query(self, filters: dict) -> list[Any]: ...
    async def get_by_session(self, session_id: str) -> list[Any]: ...
    async def verify_integrity(self, event_id: str) -> bool: ...


class IntentClassifierPort(Protocol):
    async def classify_intent(self, intent_text: str) -> tuple[str, float]: ...
    async def get_embedding(self, text: str) -> tuple[float, ...]: ...
    async def match_tool(self, embedding: tuple[float, ...]) -> tuple[str, float]: ...


class ChainPlannerPort(Protocol):
    async def plan_chain(self, intent: str, tools: list[str]) -> list[list[str]]: ...
    async def detect_circular(self, chain: list[str]) -> bool: ...
    async def validate_dependencies(self, chain: list[str]) -> bool: ...


class DriftDetectorPort(Protocol):
    async def check_drift(self, tool_name: str, behavior: dict) -> float: ...
    async def get_baseline(self, tool_name: str) -> dict | None: ...
    async def update_baseline(self, tool_name: str, behavior: dict) -> None: ...
